name: herafi_algeria
description: حرفي الجزائر - منصة ربط الزبائن بالحرفيين في الجزائر
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7

  # State
  flutter_riverpod: ^2.6.1

  # UI
  google_fonts: ^6.2.1

  # Utils
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  equatable: ^2.0.7
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/images/
    - assets/icons/
